In [ ]:
print("hello,world")



erttttttt#g

In [ ]:
pip3 install numpy






In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],
        [4,2,5],[4,2,5],[4,2,5],[4,2,5]])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.ndim

2

In [5]:
arr.shape


(5, 3)

In [6]:
arr.size

15

In [7]:
arr.dtype

dtype('int32')

In [8]:
a=np.array([[1,2,3],[4,6,5]],dtype='float')
print("array created by list:\n",a)

array created by list:
 [[1. 2. 3.]
 [4. 6. 5.]]


In [9]:
b=np.array((1,2,3))
print("array created by tuple:\n",b)

array created by tuple:
 [1 2 3]


In [10]:
 c=np.zeros((3,4))

In [11]:
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.arange?

In [16]:
np.eye?

In [18]:
f=np.arange(0,30,5)
print("\nA sequential array with steps of 5:\n",f)
#
q=np.linspace(0,5,10)
print("\nA sequential array with 10 values bt 0 and 5:\n",q)


A sequential array with steps of 5:
 [ 0  5 10 15 20 25]

A sequential array with 10 values bt 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [19]:
d=np.full((3,3),6,dtype='complex')
print("\nAn array intialized with all 6s.array type is complex:\n",d)



An array intialized with all 6s.array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [20]:
e=np.random.random((2,2))
print("\nA random array:\n",e)


A random array:
 [[0.9321333  0.1844432 ]
 [0.71173306 0.18062791]]


In [22]:
arr=np.array([[1,2,3,4],
             [5,2,4,2],
             [1,2,0,1]])
newarr=arr.reshape(2,2,3)
print("\n original array:\n",arr)
print("reshaped array:\n",newarr)


 original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [23]:
arr=np.array([[1,2,3],[4,5,6]])
flarr=arr.flatten()
print("\n original array:\n",arr)
print("\n flattened array:\n",arr)



 original array:
 [[1 2 3]
 [4 5 6]]

 flattened array:
 [[1 2 3]
 [4 5 6]]


In [24]:
arr=np.array([[-1,2,0,4],
             [4,-0.5,6,0],
             [2.6,0,7,8],
             [3,-7,4,2.0]])
temp=arr[:2,::2]
print("Array with first 2 rows and alternate columns(0 and 2):\n",temp)

Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [25]:
temp=arr[[0,1,2,3],[3,2,1,0]]
print("\nElements at indices (0,3),(1,2),(2,1),(3,0):\n",temp)


Elements at indices (0,3),(1,2),(2,1),(3,0):
 [4. 6. 0. 3.]


In [27]:
cond=arr>0
temp=arr[cond]
print("\nElement greater than 0:\n",temp)


Element greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [ ]:
#basic operations

In [28]:
a=np.array([1,2,5,3])
print("adding 1 to every element:",a+1)

adding 1 to every element: [2 3 6 4]


In [29]:
print("sub 3 to every element:",a-3)

sub 3 to every element: [-2 -1  2  0]


In [30]:
print("mul 10 to every element:",a*10)

mul 10 to every element: [10 20 50 30]


In [31]:
print("squaring   every element:",a**2)

squaring   every element: [ 1  4 25  9]


In [32]:
a*=2
print("doubled each element of original array:",a)

doubled each element of original array: [ 2  4 10  6]


In [33]:
a=np.array([[1,2,3],[3,4,5],[9,6,0]])
print("/noriginal array:/n",a)
print("Transpose of array:\n",a.T)

/noriginal array:/n [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [34]:
arr=np.array([[1,5,6],
             [4,7,3],
             [3,1,9]])
print("largest element is:",arr.max())
print("row-wise maximum elements:",arr.max(axis=1))


largest element is: 9
row-wise maximum elements: [6 7 9]


In [35]:
print("column-wise minimum elements;",arr.sum())

column-wise minimum elements; 39


In [36]:
print("cumulative sum along each row:\n",arr.cumsum(axis=1))

cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 14]
 [ 3  4 13]]


In [37]:
a=np.array([[1,2],
          [3,4]])
b=np.array([[4,3],
           [2,1]])
print("array sum:\n",a+b)

array sum:
 [[5 5]
 [5 5]]


In [38]:
print("array mul:\n",a*b)

array mul:
 [[4 6]
 [6 4]]


In [39]:
print("matrix mul:\n",a.dot(b))

matrix mul:
 [[ 8  5]
 [20 13]]


In [42]:
a=np.array([[1,4,2],
           [3,4,6],
           [0,-1,5]])
print("array element in sorted order:\n",np.sort(a,axis=None))

array element in sorted order:
 [-1  0  1  2  3  4  4  5  6]


In [43]:
print("row-wise sorted array:\n",np.sort(a,axis=1))

row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]


In [44]:
print("column wise sort by applying merge-sort:\n",np.sort(a,axis=0,kind="mergesort"))

column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


In [58]:
dtypes=[('name','S10'),('grad_year',int),('cgpa',float)]

In [59]:
values=[('hrithik',2009,8.5),('ajay',2008,8.7),('pankaj',2008,7.9),('aakash',2009,6.7)]

In [61]:
arr=np.array(values,dtype=dtypes)
print("\narray sorted by names:\n",np.sort(arr,order='name'))
print("array sorted by graduation year and then cgpa:\n",np.sort(arr,order=['grad_year','cgpa']))


array sorted by names:
 [(b'aakash', 2009, 6.7) (b'ajay', 2008, 8.7) (b'hrithik', 2009, 8.5)
 (b'pankaj', 2008, 7.9)]
array sorted by graduation year and then cgpa:
 [(b'pankaj', 2008, 7.9) (b'ajay', 2008, 8.7) (b'aakash', 2009, 6.7)
 (b'hrithik', 2009, 8.5)]


In [62]:
a=np.array([[1,2],
           [3,4]])
b=np.array([[5,6],
           [7,8]])
print("vertical stacking:\n",np.vstack((a,b)))
print("horizontal stacking:\n",np.hstack((a,b)))

vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


In [63]:
c=[5,6]
print("\ncolumn stacking:\n",np.column_stack((a,c)))


column stacking:
 [[1 2 5]
 [3 4 6]]


In [64]:
print("\nconcatenating to 2nd axis:\n",np.concatenate((a,b),1))


concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]


In [66]:
a=np.array([[1,3,5,7,9,11],
           [2,4,6,8,10,12]])
print("splitting along horizontal axis into 2 parts:\n",np.hsplit(a,2))

splitting along horizontal axis into 2 parts:
 [array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]


In [67]:
print("splitting along v axis into 2 parts:\n",np.vsplit(a,2))

splitting along v axis into 2 parts:
 [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


In [68]:
a=np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [69]:
b=np.array([1,2,3,4,5])
m=sum(b)/5
print(m)
print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [70]:
c=np.array([1,5,4,2,0])
print(np.median(c))
print(np.mean(c))

2.0
2.4


In [71]:
w=np.array([1,1,1,1,1])
print(np.average(c,weights=w))

2.4


In [72]:
u=np.mean(c)
myStd=np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

1.854723699099141


In [73]:
dev=np.std(c)
print(dev)

1.854723699099141


In [74]:
print(myStd**2)
print(np.var(c))

3.440000000000001
3.4400000000000004
